version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: movies123
      POSTGRES_DB: movies
  backend:
    container_name: backend
    build: "./server"
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - PGUSER=dev
      - PGHOST=database
      - PGPASSWORD=movies123
      - PGDATABASE=movies
      - PGPORT=5432
  frontend:
    container_name: frontend
    build: "./client"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
