export const facts = [
    "The youngest Oscar winner ever was Tatum O'Neal, who won Best Supporting Actress for Paper Moon (1973) at just 10 years old.",
    "There have been six ties in the history of the Oscars. Prior to 1950, being within three votes of the winner constituted a tie until an actual tie was necessary to give out the award to multiple contenders.",
    "The oldest Oscar winner to date was Christopher Plummer, who won Best Actor in a Supporting Role for Beginners (2010) at 82 years old.",
    "The first Academy Awards were presented in 1929 at a private dinner with about 270 guests. It was first televised in 1953, and the ceremony is now seen in more than 200 countries.",
    "Peter Finch (Network) and Heath Ledger (The Dark Knight) are the only actors to be awarded an Oscar posthumously. Ledger's Oscar was gifted to his young daughter, Matilda.",
    "Meryl Streep has been nominated for a record 21 Academy Awards, winning three Best Actress Oscars. Her most recent win was for The Iron Lady in 2011.",
    "Jack Nicholson is the most-nominated male actor, having received 12 Oscar nominations beginning with 1969's Easy Rider. His three wins tie him with Daniel Day-Lewis and Walter Brennan. Katharine Hepburn has won a record four Oscars, All Best Actresses.",
    "Ben-Hur (1959), Titanic (1997) and The Lord of the Rings: The Return of the King (2003) are the most successful films in Oscar history. They have each won 11 Oscars, with the latter winning every award for which it was nominated.",
    "In 1940, The LA Times broke the Academy's embargo and published the names of all the Oscar winners prior to the ceremony. After this, the Academy introduced the sealed envelope tradition that is still practiced to this day.",
    "Bob Hope hosted the ceremony an impressive 19 times, making him the most frequent Oscar host ever.",
    "Walt Disney has the most Oscar wins of all time. In all, he has won 22 competitive Oscars and 3 honorary ones, out of a total of 59 nominations. He was nominated for one Oscar every year between 1942 and 1963.",
    "Oscar winners don't really own their statues. Upon being presented with the trophy, winners must sign an agreement stating that should they wish to sell their statuettes, they must first offer them to the Academy for $1. If they refuse, they cannot keep their trophy.",
    "After the 2002 ceremony, where the show ran for an astounding four hours and twenty-three minutes, the Academy enacted the 45-second rule. Speeches longer than this time frame are therefore cut off by the orchestra.",
    "The record for the shortest acceptance speech is shared by renowned director Alfred Hitchcock and William Holden. They both simply said, 'Thank you.'",
    "Diane Keaton is the sole actor to be nominated for exactly one award over four consecutive decades. She won for 1977's Annie Hall and lost for 1981's Reds. Fifteen years later she received her third nomination for Marvin's Room (1996) and her last in 2003's Something's Gotta Give.",
    "The red carpet is 500 feet long and is 16,500 square feet.",
    "Jennifer Lawrence wore the most expensive dress in Oscars history at the 2013 ceremony: her bluish-pink Dior Couture ballgown valued at a whopping $4 million when it was lent to her.",
    "Liza Minnelli became the only Oscar recipient whose parents were also Oscar winners, after nabbing the award for Best Actress for Cabaret (1972). Her mother, Judy Garland, received an honorary award in 1939 and her father, Vincente Minnelli, won Best Director for Gigi (1958).",
    "Kathryn Bigalow became the first woman in history to win the Best Director Award for her film The Hurt Locker (2009).",
    "Midnight Cowboy (1969) is the only x-rated film to win the Best Picture award.",
    "Italy is the country with the most number of wins for Foreign Language Film at the Oscars, with 10 wins.",
    "The only sequel to have won Best Picture is The Godfather: Part II (1974).",
]
